conn = sqlite3.connect('BUS_LIST.db')
            c = conn.cursor()
            value1=(p.get())
            value2=(q.get())
            value3=(r.get())
            c.execute("SELECT * FROM bb_bus WHERE D_FROM= ? AND A_TO = ?  ",(an,bn))
            conn.commit()
            ro=c.fetchall()
            for i in ro:
                qwerty=Label(op,text=i , bg="yellow")
                qwerty.pack(padx=5,pady=20,side=LEFT).pack(padx=40)
                qwe=Label(op,text='')
                qwe.pack()
            print(ro)
            conn.close()